export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const INCREASE_QUANTITY='INCREASE_QUANTITY';
export const DECREASE_QUANTITY = "DECREASE_QUANTITY";
export const DELETE_ITEM_FROM_CART = "DELETE_ITEM_FROM_CART";
